theme: jekyll-theme-cayman
title: Theresa Thorne
description: I'm passionate about using code to solve problems and simplify processes,
and I'm excited about the mobile & responsive future of the web. 
